"""Initial schema.

Creates the market intelligence schema described in docs/01-data-model.md.

Generated from the SQLAlchemy models rather than by diffing a live database, so
that the first migration is reproducible from source alone. Subsequent
migrations should be produced with ``alembic revision --autogenerate``.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-27
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.CheckConstraint('rate > 0', name='ck_fx_rate_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'as_of', name='uq_fx_pair_date')
    )
    op.create_index('ix_fx_pair_date', 'fx_rates', ['base_currency', 'quote_currency', 'as_of'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('config_id', sa.String(length=32), nullable=True),
    sa.Column('model_key', sa.String(length=128), nullable=True),
    sa.Column('generation_key', sa.String(length=192), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('price_basis', sa.String(length=16), nullable=False),
    sa.Column('median_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mean_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('p10_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('p25_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('p75_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('p90_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dispersion', sa.Float(), nullable=True),
    sa.Column('median_mileage_km', sa.Integer(), nullable=True),
    sa.Column('median_days_on_market', sa.Float(), nullable=True),
    sa.Column('new_listings', sa.Integer(), nullable=False),
    sa.Column('removed_listings', sa.Integer(), nullable=False),
    sa.Column('price_reductions', sa.Integer(), nullable=False),
    sa.Column('median_reduction_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'region', 'snapshot_date', 'window_days', name='uq_snapshot_scope')
    )
    op.create_index('ix_snapshot_config_date', 'market_snapshots', ['config_id', 'snapshot_date'], unique=False)
    op.create_index('ix_snapshot_model_date', 'market_snapshots', ['model_key', 'snapshot_date'], unique=False)
    op.create_table('market_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trust_weight', sa.Float(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('plan', sa.String(length=24), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_email', 'users', ['email'], unique=False)
    op.create_table('vehicle_configurations',
    sa.Column('config_id', sa.String(length=32), nullable=False),
    sa.Column('model_key', sa.String(length=128), nullable=False),
    sa.Column('generation_key', sa.String(length=192), nullable=False),
    sa.Column('powertrain_key', sa.String(length=384), nullable=False),
    sa.Column('canonical_string', sa.String(length=512), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=96), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('generation', sa.String(length=64), nullable=True),
    sa.Column('trim', sa.String(length=96), nullable=True),
    sa.Column('engine_code', sa.String(length=48), nullable=True),
    sa.Column('displacement_l', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('fuel', sa.String(length=24), nullable=False),
    sa.Column('transmission', sa.String(length=24), nullable=False),
    sa.Column('drivetrain', sa.String(length=16), nullable=False),
    sa.Column('body', sa.String(length=24), nullable=False),
    sa.Column('horsepower', sa.Integer(), nullable=True),
    sa.Column('import_status', sa.String(length=24), nullable=False),
    sa.Column('specificity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('model_year IS NULL OR (model_year BETWEEN 1900 AND 2100)', name='ck_config_model_year_range'),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index('ix_config_generation_key', 'vehicle_configurations', ['generation_key'], unique=False)
    op.create_index('ix_config_make_model_year', 'vehicle_configurations', ['make', 'model', 'model_year'], unique=False)
    op.create_index('ix_config_model_key', 'vehicle_configurations', ['model_key'], unique=False)
    op.create_index('ix_config_powertrain_key', 'vehicle_configurations', ['powertrain_key'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_created', 'audit_log', ['action', 'created_at'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('listings_seen', sa.Integer(), nullable=False),
    sa.Column('listings_created', sa.Integer(), nullable=False),
    sa.Column('listings_updated', sa.Integer(), nullable=False),
    sa.Column('listings_removed', sa.Integer(), nullable=False),
    sa.Column('price_changes', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('requests_made', sa.Integer(), nullable=False),
    sa.Column('robots_denied', sa.Integer(), nullable=False),
    sa.Column('field_extraction_rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unmapped_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['market_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_source_started', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('config_id', sa.String(length=32), nullable=True),
    sa.Column('model_key', sa.String(length=128), nullable=True),
    sa.Column('generation_key', sa.String(length=192), nullable=True),
    sa.Column('powertrain_key', sa.String(length=384), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('price_azn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fx_rate_used', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fx_rate_source', sa.String(length=64), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('seller_type', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('has_damage_disclosure', sa.Boolean(), nullable=True),
    sa.Column('has_repaint_disclosure', sa.Boolean(), nullable=True),
    sa.Column('owner_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('last_seen_at >= first_seen_at', name='ck_listing_seen_order'),
    sa.CheckConstraint('mileage_km IS NULL OR mileage_km >= 0', name='ck_listing_mileage_non_negative'),
    sa.CheckConstraint('price_azn >= 0', name='ck_listing_price_non_negative'),
    sa.ForeignKeyConstraint(['config_id'], ['vehicle_configurations.config_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['market_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_listing_source_external')
    )
    op.create_index('ix_listing_config_seen', 'listings', ['config_id', 'last_seen_at'], unique=False)
    op.create_index('ix_listing_generation_key_seen', 'listings', ['generation_key', 'last_seen_at'], unique=False)
    op.create_index('ix_listing_model_key_seen', 'listings', ['model_key', 'last_seen_at'], unique=False)
    op.create_index('ix_listing_region_seen', 'listings', ['region', 'last_seen_at'], unique=False)
    op.create_index('ix_listing_status_seen', 'listings', ['status', 'last_seen_at'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.String(length=32), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('asking_price_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('central_estimate_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fair_market_low_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fair_market_high_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_basis', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.String(length=24), nullable=False),
    sa.Column('price_difference_pct', sa.Float(), nullable=True),
    sa.Column('price_percentile', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('comparable_count', sa.Integer(), nullable=False),
    sa.Column('evidence_bundle', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_source', sa.String(length=24), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_analysis_confidence_range'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='ck_analysis_risk_range'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index('ix_analysis_config', 'analysis_results', ['config_id'], unique=False)
    op.create_index('ix_analysis_user_created', 'analysis_results', ['user_id', 'created_at'], unique=False)
    op.create_table('data_quality_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=True),
    sa.Column('issue', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('raw_value', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['market_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_field', 'data_quality_observations', ['field_name'], unique=False)
    op.create_index('ix_quality_issue_time', 'data_quality_observations', ['issue', 'observed_at'], unique=False)
    op.create_table('listing_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_azn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('change_kind', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observation_kind_time', 'listing_observations', ['change_kind', 'observed_at'], unique=False)
    op.create_index('ix_observation_listing_time', 'listing_observations', ['listing_id', 'observed_at'], unique=False)
    op.create_table('risk_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('config_id', sa.String(length=32), nullable=True),
    sa.Column('risk_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_listing', 'risk_observations', ['listing_id'], unique=False)
    op.create_index('ix_risk_type_observed', 'risk_observations', ['risk_type', 'observed_at'], unique=False)
    op.create_table('saved_vehicles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('analysis_id', sa.String(length=32), nullable=True),
    sa.Column('config_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('target_price_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notify_on_price_drop', sa.Boolean(), nullable=False),
    sa.Column('notify_on_removal', sa.Boolean(), nullable=False),
    sa.Column('last_seen_price_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_saved_user_listing')
    )
    op.create_index('ix_saved_user', 'saved_vehicles', ['user_id'], unique=False)
    op.create_table('transaction_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('config_id', sa.String(length=32), nullable=True),
    sa.Column('model_key', sa.String(length=128), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('price_azn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('listed_price_azn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_transaction_confidence'),
    sa.CheckConstraint('price_azn > 0', name='ck_transaction_price_positive'),
    sa.ForeignKeyConstraint(['config_id'], ['vehicle_configurations.config_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_config_date', 'transaction_observations', ['config_id', 'transaction_date'], unique=False)
    op.create_index('ix_transaction_model_date', 'transaction_observations', ['model_key', 'transaction_date'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('saved_vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['saved_vehicle_id'], ['saved_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_saved_created', 'alert_events', ['saved_vehicle_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_saved_created', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_transaction_model_date', table_name='transaction_observations')
    op.drop_index('ix_transaction_config_date', table_name='transaction_observations')
    op.drop_table('transaction_observations')
    op.drop_index('ix_saved_user', table_name='saved_vehicles')
    op.drop_table('saved_vehicles')
    op.drop_index('ix_risk_type_observed', table_name='risk_observations')
    op.drop_index('ix_risk_listing', table_name='risk_observations')
    op.drop_table('risk_observations')
    op.drop_index('ix_observation_listing_time', table_name='listing_observations')
    op.drop_index('ix_observation_kind_time', table_name='listing_observations')
    op.drop_table('listing_observations')
    op.drop_index('ix_quality_issue_time', table_name='data_quality_observations')
    op.drop_index('ix_quality_field', table_name='data_quality_observations')
    op.drop_table('data_quality_observations')
    op.drop_index('ix_analysis_user_created', table_name='analysis_results')
    op.drop_index('ix_analysis_config', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('ix_listing_status_seen', table_name='listings')
    op.drop_index('ix_listing_region_seen', table_name='listings')
    op.drop_index('ix_listing_model_key_seen', table_name='listings')
    op.drop_index('ix_listing_generation_key_seen', table_name='listings')
    op.drop_index('ix_listing_config_seen', table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_run_source_started', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_audit_action_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_config_powertrain_key', table_name='vehicle_configurations')
    op.drop_index('ix_config_model_key', table_name='vehicle_configurations')
    op.drop_index('ix_config_make_model_year', table_name='vehicle_configurations')
    op.drop_index('ix_config_generation_key', table_name='vehicle_configurations')
    op.drop_table('vehicle_configurations')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_table('users')
    op.drop_table('market_sources')
    op.drop_index('ix_snapshot_model_date', table_name='market_snapshots')
    op.drop_index('ix_snapshot_config_date', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_fx_pair_date', table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
