"""user profile fields and sessions

Revision ID: 108dcb7d4082
Revises: 0001_initial
Create Date: 2026-08-30 14:35:37.323729
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '108dcb7d4082'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_session_token_hash', 'user_sessions', ['token_hash'], unique=False)
    op.create_index('ix_session_user', 'user_sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_year')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index('ix_session_user', table_name='user_sessions')
    op.drop_index('ix_session_token_hash', table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
